package javaapplication30.views;

import java.io.PrintWriter;
import java.util.Arrays;
import javaapplication30.TugasBesar;
import javax.swing.JOptionPane;

/**
 *
 * @author asrulsibaoel
 */
public class LembarKerja extends javax.swing.JFrame implements View {

    private TugasBesar tugasBesar;
    private int nomorSoal = 0;
    private String[] soal;
    private int jumlahBenar = 0;

    /**
     *
     * @param tugasBesar
     */
    public LembarKerja(TugasBesar tugasBesar) {
        this.tugasBesar = tugasBesar;
        initComponents();
    }

    /**
     * Creates new form LembarKerja
     */
    public LembarKerja() {
        initComponents();
    }

    public int getNomorSoal() {
        return nomorSoal;
    }

    public void setNomorSoal(int nomorSoal) {
        this.nomorSoal = nomorSoal;
    }

    public int getJumlahBenar() {
        return jumlahBenar;
    }

    public void setJumlahBenar(int jumlahBenar) {
        this.jumlahBenar = jumlahBenar;
    }

    public void getSoal() {
        soal = this.tugasBesar.getSoal()[nomorSoal];

        jLabel1.setText(soal[0]);
        jRadioButton1.setText(soal[1]);
        jRadioButton2.setText(soal[2]);
        jRadioButton3.setText(soal[3]);
        jRadioButton4.setText(soal[4]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Selanjutnya");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Soal dsfjsdfbgsdkfgnsdjhfgsdf");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addGap(233, 233, 233)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(22, 22, 22)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (nomorSoal == 9) {
            //tampilkan nilai
            if (jumlahBenar > 0) {
                this.tugasBesar.getHasilNilai().setNilai(jumlahBenar * 10 + "");
            } else {
                this.tugasBesar.getHasilNilai().setNilai(0 + "");
            }

            this.setVisible(false);
            this.tugasBesar.getHasilNilai().setVisible(true);
            this.tugasBesar.getHasilNilai().getjLabel2().setText(this.tugasBesar.getHasilNilai().getNilai());
            String report = "==================================\n"
                    + "Nama : " + this.tugasBesar.getSession()[0] + "\n"
                    + "NRP : " + this.tugasBesar.getSession()[1] + "\n"
                    + "Nilai : " + (jumlahBenar * 10) + ""
                    + "==================================\n";
            try {
                printOut(report);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

        }

        if (nomorSoal < 10) {
            //proses perhitungan nilai

            String jawaban;
            if (jRadioButton1.isSelected()) {
                jawaban = "A";
            } else if (jRadioButton2.isSelected()) {
                jawaban = "B";
            } else if (jRadioButton3.isSelected()) {
                jawaban = "C";
            } else {
                jawaban = "D";
            }

            cekJawaban(jawaban);

            //tampilkan soal selanjutnya
            nomorSoal++;
            try {
                getSoal();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        System.out.println(jumlahBenar);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Cek jawaban siswa
     *
     * @param jawaban
     */
    private void cekJawaban(String jawaban) {
        System.out.println("kunci : " + soal[5] + ", jawaban" + jawaban);
        if (soal[5].equals(jawaban)) {
            jumlahBenar += 1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LembarKerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LembarKerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LembarKerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LembarKerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LembarKerja().setVisible(true);
        });
    }

    @Override
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(null, message);
    }

    @Override
    public void showWindow() {
        this.setVisible(true); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void hideWindow() {
        this.setVisible(false); //To change body of generated methods, choose Tools | Templates.
    }

    private void printOut(String text) throws Exception {
        try (PrintWriter out = new PrintWriter("report.txt")) {
            out.println(text);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
